In [1]:
import sys
sys.path.insert(0,'C:\\Users\\Syahrir Ridha\\PycharmProjects\\NET_Solver\\')
import torch
import numpy as np
from models import *
from torch.utils.data import Dataset

In [2]:
X = torch.linspace(0,1, 10)
Y = torch.linspace(0,1,10)
xx, yy = torch.meshgrid(X,Y)

In [3]:
dx = X[1]-X[0]
dy = Y[1] - Y[0]

In [4]:
xx

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111, 0.1111,
         0.1111],
        [0.2222, 0.2222, 0.2222, 0.2222, 0.2222, 0.2222, 0.2222, 0.2222, 0.2222,
         0.2222],
        [0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333, 0.3333,
         0.3333],
        [0.4444, 0.4444, 0.4444, 0.4444, 0.4444, 0.4444, 0.4444, 0.4444, 0.4444,
         0.4444],
        [0.5556, 0.5556, 0.5556, 0.5556, 0.5556, 0.5556, 0.5556, 0.5556, 0.5556,
         0.5556],
        [0.6667, 0.6667, 0.6667, 0.6667, 0.6667, 0.6667, 0.6667, 0.6667, 0.6667,
         0.6667],
        [0.7778, 0.7778, 0.7778, 0.7778, 0.7778, 0.7778, 0.7778, 0.7778, 0.7778,
         0.7778],
        [0.8889, 0.8889, 0.8889, 0.8889, 0.8889, 0.8889, 0.8889, 0.8889, 0.8889,
         0.8889],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000]])

In [5]:
yy

tensor([[0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
         1.0000],
        [0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
         1.0000],
        [0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
         1.0000],
        [0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
         1.0000],
        [0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
         1.0000],
        [0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
         1.0000],
        [0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
         1.0000],
        [0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
         1.0000],
        [0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
         1.0000],
        [0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
         1.0000]])

In [6]:
data = torch.cat((xx.reshape(-1,1),yy.reshape(-1,1)),1)

In [7]:
data.shape

torch.Size([100, 2])

In [8]:
data[data[:,0]==0.5]

tensor([], size=(0, 2))

In [9]:
data[data[:,0]==0+dx]

tensor([[0.1111, 0.0000],
        [0.1111, 0.1111],
        [0.1111, 0.2222],
        [0.1111, 0.3333],
        [0.1111, 0.4444],
        [0.1111, 0.5556],
        [0.1111, 0.6667],
        [0.1111, 0.7778],
        [0.1111, 0.8889],
        [0.1111, 1.0000]])

In [10]:
def get_index(host, target):
        """
        :param host: Tensor which contains the target values
        :param target: Tensor who's index is to be determined in the host
        :return: index of the target Tensor with respect to the host Tensor
        """
        # host, target = host.reshape(host.size(-1),1), target.reshape(target.size(-1),1)
        diff = target.unsqueeze(1) - host.unsqueeze(0)
        dsum = torch.abs(diff).sum(-1)
        loc = (dsum < 1e-5).nonzero(as_tuple=False)
        return loc[:, -1]

In [11]:
# data[:,:]==1

In [12]:
data[get_index(data, data[data[:,0]==])]

SyntaxError: invalid syntax (<ipython-input-12-56d49e0322e6>, line 1)

In [ ]:
#define a neural net
activation = torch.nn.Tanh()
net = MLP(2, 1, 2, 1, act=activation)
out_data = net(data)

In [ ]:
x, y = np.linspace(0,1,10), np.linspace(0,1,10)

In [ ]:
class Hard_Diri:
    def __init__(self, data, device='cpu', compt = 'on'):
        if compt == 'on':
            x = np.stack(np.meshgrid(*data[0]), -1).reshape(-1, len(data[0]))
            y = np.stack(data[1], axis=1)

        elif compt == 'off':
            x = np.stack(tuple(data[0]),-1).reshape(-1, len(data[0]))
            y = np.stack(data[1], axis=1)

        assert len(x) == len(y), f'The input has shape of {x.shape} and output has {y.shape}'

        self.x = torch.from_numpy(x).float().to(device)
        self.y = torch.from_numpy(y).float().to(device)


class Hard_Dirichlet:
    def __init__(self, x, y, mesh=True):
        
        assert isinstance(x, dict), f'Input data must be in dict format'
        assert isinstance(y, dict), f'Output data must be in dict format'
        
        self.variable = [tuple(x.keys()), tuple(y.keys())]
        self.data = [x.values(), list(y.values())]
        
        data_in = np.stack(np.meshgrid(*self.data[0]), -1).reshape(-1, len(self.data[0]))
        data_out = np.stack(self.data[1], axis=1)
        
        self.in_data = torch.from_numpy(data_in).float()
        self.out_data = torch.from_numpy(data_out).float()
        
        assert len(self.in_data) == len(self.out_data), f'Input has shape of {self.in_data.shape} and Output has shape of {self.out_data.shape}'
        
    def Dirichlet(self, data, model_pred):
        # check for data index 
        index_diri = get_index(data, self.in_data)
        model_pred[index_diri] = 0
        return model_pred

In [ ]:
diri = Hard_Dirichlet({'x':x, 'y': [0,1]}, {'u':np.full(2*len(x), -1)})
#test_out = diri.Dirichlet(data, out_data)

In [ ]:
idx = get_index(data, diri.in_data)

In [ ]:
# def set_differ(A, B):
#     r"""Returns the elements of A without the elements of B"""
#     mask = torch.as_tensor([elem not in B for elem in A])
#     return A[mask]

In [86]:
def slice_data(A, B):
    # https://discuss.pytorch.org/t/any-way-of-filtering-given-rows-from-a-tensor-a/83828/2
    r"""Returns the elements of A without the elements of B"""
    cdist = torch.cdist(A.float(), B.float(),p=1)
    min_dist = torch.min(cdist, dim=1).values
    return A[min_dist>0.000007]

In [ ]:
slice_data(data, diri.in_data).shape

In [ ]:
x_ = [0,1]
y_ = np.linspace(0,1,70)
xx,yy = np.meshgrid(x_,y_)

In [ ]:
np.random.randn(2,2) * np.random.randn(2,2)

In [117]:
class Hard_Boundary:
    def __init__(self, dirichlet, neumann):
        assert isinstance(dirichlet, dict), f'The Dirichlet data boundary should be in dict format'
        assert isinstance(neumann, dict), f'The Neumann data boundary should be in dict format'
        
        self.diri = dirichlet
        self.numann = neumann
    
    def Dirichelt(self):
        var = tuple(self.diri.keys())
        data = self.diri.values()
        in_data = np.stack(np.meshgrid(*data), -1).reshape(-1, len(data))
        in_data = torch.from_numpy(in_data).float()
        return in_data
    
    def Neumann(self):
        var = tuple(self.numann.keys())
        data = self.numann.values()
        in_data = np.stack(np.meshgrid(*data), -1).reshape(-1, len(data))
        in_data = torch.from_numpy(in_data).float()
        return in_data
    
    def slice_data(self, model_data, tol =0.000007 ):
        # combine the data from neumann and dirichlet
        combo_data = torch.cat((self.Dirichelt(), self.Neumann()), dim=0)
        
        # return the elements of model data without the boundary data for hard boundary 
        # implementation
        # https://discuss.pytorch.org/t/any-way-of-filtering-given-rows-from-a-tensor-a/83828/2
        cdist = torch.cdist(model_data, combo_data,p=1)
        min_dist = torch.min(cdist, dim=1).values
        
        # return the tensor
        return model_data[min_dist> tol ]

In [118]:
arr = np.array([0,1])
split = np.linspace(0,1,10)
test = Hard_Boundary(dirichlet={'x':arr,'y':split}, neumann={'x':split, 'y':arr})

In [119]:
# slice_data(data, test.slice_data())
test.slice_data(data).shape

torch.Size([64, 2])

In [113]:
test_neu = test.Neumann()
test_diir = test.Dirichelt()

In [114]:
torch.cat((test_neu, test_diir), dim=0).shape

torch.Size([40, 2])

In [120]:
test.slice_data(data)

tensor([[0.1111, 0.1111],
        [0.1111, 0.2222],
        [0.1111, 0.3333],
        [0.1111, 0.4444],
        [0.1111, 0.5556],
        [0.1111, 0.6667],
        [0.1111, 0.7778],
        [0.1111, 0.8889],
        [0.2222, 0.1111],
        [0.2222, 0.2222],
        [0.2222, 0.3333],
        [0.2222, 0.4444],
        [0.2222, 0.5556],
        [0.2222, 0.6667],
        [0.2222, 0.7778],
        [0.2222, 0.8889],
        [0.3333, 0.1111],
        [0.3333, 0.2222],
        [0.3333, 0.3333],
        [0.3333, 0.4444],
        [0.3333, 0.5556],
        [0.3333, 0.6667],
        [0.3333, 0.7778],
        [0.3333, 0.8889],
        [0.4444, 0.1111],
        [0.4444, 0.2222],
        [0.4444, 0.3333],
        [0.4444, 0.4444],
        [0.4444, 0.5556],
        [0.4444, 0.6667],
        [0.4444, 0.7778],
        [0.4444, 0.8889],
        [0.5556, 0.1111],
        [0.5556, 0.2222],
        [0.5556, 0.3333],
        [0.5556, 0.4444],
        [0.5556, 0.5556],
        [0.5556, 0.6667],
        [0.5