In [1]:
# this is the trial implementation of neural network trial solution of 2 side dirichlet and 2 side neumann boundary condition
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import sys
sys.path.insert(0,'C:\\Users\\Syahrir Ridha\\PycharmProjects\\NET_Solver\\')
from models import*

In [2]:
# import a neural network
in_dim = 2
out_dim = 1
hid_dim = 4
layers = 2
act = torch.nn.Tanh()
net = MLP(in_dim, out_dim, hid_dim, layers, act=act)

In [3]:
def radial_bipolar(r_out, r_inn, ecc):
    r = r_inn/r_out
    xi_out = np.arccosh( (r*(1+ecc**2) + (1-ecc**2)) / (2*r*ecc) )
    xi_inn = np.arccosh( (r*(1-ecc**2) + (1+ecc**2)) / (2*ecc) )
    c_1 = r_inn*np.sinh(xi_out)
    c_2 = r_out*np.sinh(xi_inn)
    np.testing.assert_allclose(c_1, c_2, rtol=1e-10, atol=0)
    return xi_out, xi_inn, c_1
r_out = 1.0
r_inn = 0.6
ecc = 0.001
xi_out, xi_inn, c = radial_bipolar(r_out,r_inn, ecc)
print(f'Outer Xi: {xi_out} Inner Xi: {xi_inn} Focal Point: {c}')

Outer Xi: 7.8885841413687325 Inner Xi: 7.377758767602808 Focal Point: 799.9995749999124


In [4]:
# define the mesh
nx = 8
ny = 8
xi_, eta_ = np.linspace(xi_inn, xi_out, nx), np.linspace(0, np.pi, ny)
xi, eta = np.meshgrid(xi_, eta_)
# prepare input data for neural network
xi, eta = torch.Tensor(xi).float().reshape(-1,1), torch.Tensor(eta).float().reshape(-1,1)
input_data = torch.cat([xi,eta], dim=1)

In [8]:
# # consider a PDE equation Phi with following boundar conditions
# # Phi(0,y) = 0
# # Phi(1,y) = 0
# # d_Phi(x,0)/d_y = 0
# # d_Phi(x,1)/d_y = 0
# A = 0
# B = 0
# C = 0
# D = 0
# x = data[:,0].reshape(-1,1)
# y = data[:,1].reshape(-1,1)

NameError: name 'data' is not defined

In [9]:
trial = ((1-x)*A + x*B + ((1 - y)*( C - ( (1-x)*C + x*C ) )) + (y* ( D - ( (1-x)*D +x*D ) )) + 
         x*(1-x)*y*(1- y)*net(data) )

NameError: name 'x' is not defined

In [11]:
trial_test = ((xi_out-xi)*A + x*B + 
             
         x*(1-x)*net(input_data) )

NameError: name 'x' is not defined

In [82]:
trial_test.reshape(ny,nx)

tensor([[ 0.0000, -0.0143, -0.0239, -0.0287, -0.0288, -0.0240, -0.0144,  0.0000],
        [ 0.0000, -0.0143, -0.0239, -0.0287, -0.0288, -0.0240, -0.0144,  0.0000],
        [ 0.0000, -0.0143, -0.0239, -0.0287, -0.0288, -0.0240, -0.0144,  0.0000],
        [ 0.0000, -0.0143, -0.0239, -0.0287, -0.0288, -0.0240, -0.0144,  0.0000],
        [ 0.0000, -0.0143, -0.0239, -0.0287, -0.0288, -0.0240, -0.0144,  0.0000],
        [ 0.0000, -0.0143, -0.0239, -0.0287, -0.0288, -0.0240, -0.0144,  0.0000],
        [ 0.0000, -0.0143, -0.0239, -0.0287, -0.0288, -0.0240, -0.0144,  0.0000],
        [ 0.0000, -0.0143, -0.0238, -0.0287, -0.0288, -0.0240, -0.0144,  0.0000]],
       grad_fn=<ViewBackward>)

In [13]:
((xi-xi_inn)*(xi_out-xi)*net(input_data)).reshape(-1,nx)

tensor([[0.0000, 0.0066, 0.0111, 0.0133, 0.0133, 0.0111, 0.0067, 0.0000],
        [0.0000, 0.0066, 0.0111, 0.0133, 0.0133, 0.0111, 0.0066, 0.0000],
        [0.0000, 0.0066, 0.0110, 0.0133, 0.0133, 0.0111, 0.0066, 0.0000],
        [0.0000, 0.0066, 0.0110, 0.0132, 0.0132, 0.0110, 0.0066, 0.0000],
        [0.0000, 0.0066, 0.0110, 0.0132, 0.0132, 0.0110, 0.0066, 0.0000],
        [0.0000, 0.0066, 0.0110, 0.0132, 0.0132, 0.0110, 0.0066, 0.0000],
        [0.0000, 0.0066, 0.0110, 0.0132, 0.0132, 0.0110, 0.0066, 0.0000],
        [0.0000, 0.0066, 0.0110, 0.0132, 0.0132, 0.0110, 0.0066, 0.0000]],
       grad_fn=<ViewBackward>)

In [69]:
xi

array([[7.37775877, 7.45073382, 7.52370887, 7.59668393, 7.66965898,
        7.74263403, 7.81560909, 7.88858414],
       [7.37775877, 7.45073382, 7.52370887, 7.59668393, 7.66965898,
        7.74263403, 7.81560909, 7.88858414],
       [7.37775877, 7.45073382, 7.52370887, 7.59668393, 7.66965898,
        7.74263403, 7.81560909, 7.88858414],
       [7.37775877, 7.45073382, 7.52370887, 7.59668393, 7.66965898,
        7.74263403, 7.81560909, 7.88858414],
       [7.37775877, 7.45073382, 7.52370887, 7.59668393, 7.66965898,
        7.74263403, 7.81560909, 7.88858414],
       [7.37775877, 7.45073382, 7.52370887, 7.59668393, 7.66965898,
        7.74263403, 7.81560909, 7.88858414],
       [7.37775877, 7.45073382, 7.52370887, 7.59668393, 7.66965898,
        7.74263403, 7.81560909, 7.88858414],
       [7.37775877, 7.45073382, 7.52370887, 7.59668393, 7.66965898,
        7.74263403, 7.81560909, 7.88858414],
       [7.37775877, 7.45073382, 7.52370887, 7.59668393, 7.66965898,
        7.74263403, 7.815609